name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_PASS }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag simonbv19/express-randomquotes:latest

      - name: Docker Push
        run: docker push simonbv19/express-randomquotes:latest
